### ISSUE TITLE
panic on sync with local git repo and version=HEAD

### ISSUE THREAD

**Issue by paulhankin** [daedaleanai/dbt#97]
I have a MODULE file like this:

    version: 2
    dependencies:
      dbt-rules:
        url: /home/ph/code/dbt-rules/.git
        version: HEAD

When I run "dbt sync" I get:

```
Updating PROJECT_NAME_REMOVED
  Depends on dbt-rules
    Cloning '/home/ph/code/dbt-rules/.git'.
    Resolved dependency version 'HEAD' to hash 'ae299fa648...'
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/daedaleanai/dbt/cmd.runSync(0xaf9fc0, 0xb2e718, 0x0, 0x0)
	/home/ph/go/pkg/mod/github.com/daedaleanai/dbt@v1.2.0/cmd/sync.go:137 +0xfc8
github.com/daedaleanai/cobra.(*Command).execute(0xaf9fc0, 0xb2e718, 0x0, 0x0, 0xaf9fc0, 0xb2e718)
	/home/ph/go/pkg/mod/github.com/daedaleanai/cobra@v1.1.2/command.go:856 +0x2c2
github.com/daedaleanai/cobra.(*Command).ExecuteC(0xaf9ac0, 0xb2e4d1, 0x85a482, 0x7)
	/home/ph/go/pkg/mod/github.com/daedaleanai/cobra@v1.1.2/command.go:960 +0x375
github.com/daedaleanai/cobra.(*Command).Execute(...)
	/home/ph/go/pkg/mod/github.com/daedaleanai/cobra@v1.1.2/command.go:897
github.com/daedaleanai/dbt/cmd.Execute()
	/home/ph/go/pkg/mod/github.com/daedaleanai/dbt@v1.2.0/cmd/root.go:26 +0x9f
main.main()
	/home/ph/go/pkg/mod/github.com/daedaleanai/dbt@v1.2.0/main.go:6 +0x25

```

**Comment by paulhankin** [comment]
Actually, maybe it's because I deleted the pinneddependencies section from my MODULE file manually because I forgot how to do it with dbt sync --update.

**Comment by paulhankin** [comment]
Repro: delete everything in a MODULE file after "pinneddependencies:".

In this case, YAML decoding yields a nil map, over-writing the non-nil empty map that's already there. See: https://github.com/go-yaml/yaml/issues/347
